# Generated by Django 5.1.6 on 2025-02-20 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emergency", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("reported", "Reported"), ("resolved", "Resolved")],
                        default="reported",
                        max_length=50,
                    ),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_cases",
                        to="emergency.staff",
                    ),
                ),
            ],
        ),
    ]
