# Generated by Django 5.1.6 on 2025-03-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emergency", "0002_case"),
    ]

    operations = [
        migrations.CreateModel(
            name="type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emergency_category", models.CharField(max_length=100)),
                ("emergency_type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
