# Generated by Django 5.1.6 on 2025-03-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emergency", "0003_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="location",
        ),
        migrations.AddField(
            model_name="case",
            name="latitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="case",
            name="longitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="case",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="case_pictures/"),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[("Reported", "Reported"), ("Resolved", "Resolved")],
                default="Reported",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
