# Generated by Django 5.1.6 on 2025-03-25 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "emergency",
            "0004_remove_case_location_case_latitude_case_longitude_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emergency_category", models.CharField(max_length=100)),
                ("emergency_type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="type",
        ),
        migrations.AlterField(
            model_name="case",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="emergency.emergencytype",
            ),
        ),
    ]
