# Generated by Django 5.1.6 on 2025-03-25 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emergency", "0005_emergencytype_delete_type_alter_case_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="emergency.emergencytype",
            ),
        ),
    ]
