# Generated by Django 5.1.6 on 2025-03-25 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emergency", "0006_alter_case_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="picture",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="case_pictures/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="case",
            name="title",
            field=models.CharField(max_length=10),
        ),
    ]
